import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "sora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          fontFamily: "-apple-system, BlinkMacSystemFont",
        }}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
